apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-metrics-app
spec:
  replicas: 1 # Number of pods
  selector:
    matchLabels:
      app: flask-metrics-app
  template:
    metadata:
      labels:
        app: flask-metrics-app
    spec:
      containers:
      - name: flask-metrics-app
        image: flask-metrics-app:latest
        imagePullPolicy: Never  # Tell Kubernetes not to pull from a registry
        # image: vikash95/kubernetes-test-app:latest
        env:
        - name: CAPSTONE_TEST
          value: "b373d84d2ba1ce614febbe2edf1b5ca82beb8e30"
        resources:
          limits:
            memory: "3Gi"
            cpu: "1"
          requests:
            memory: "2Gi"
            cpu: "500m"
        ports:
        - containerPort: 5001
---
---
apiVersion: v1
kind: Service
metadata:
  name: flask-metrics-app
spec:
  type: LoadBalancer       # <-- add this
  selector:
    app: flask-metrics-app
  ports:
    - port: 8080
      targetPort: 5001
      nodePort: 30001   # <-- optional, can pick any port 30000-32767
